### ISSUE TITLE
Firebase distribution with github actions. 

### ISSUE THREAD

**Issue by shashankdaima** [KalleHallden/exer_log#123]
@KalleHallden I was thinking it would be good if we can add firebase distribution for bunch of testers/contributors. It is super simple, I am pasting a yaml file that I use for almost all my projects. 
```yaml
name: Android Firebase CI
'on':
  push:
    branches:
      - stable
  pull_request:
    branches:
      - stable
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK v11
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter pub get
      
      # Build apk.
      - run: flutter build apk --debug #add you firebase command if it is different
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@master
        with:
          appId: '${{secrets.FIREBASE_APP_ID}}'
          token: '${{secrets.FIREBASE_TOKEN}}'
          groups: group1 #<GROUP NAME>
          file: build/app/outputs/flutter-apk/app-debug.apk

```
